server:
  port: 8761

spring:
  application:
    name: discoveryservice #spring? ???? ??ID

eureka:
  client:
    register-with-eureka: false # default true. ????  ??? ?? ????
    fetch-registry: false
